apiVersion: v1
kind: Service
metadata:
  name: mongo-client-service
  labels:
    app: mongo-client
spec:
  selector:
    app: mongo-client
  ports:
    - protocol: TCP
      port: 27017        
      targetPort: 27017 
  clusterIP: None      
